# Book settings
title: 可能性の獣
author: syamaguc
copyright: "2021" # Copyright year to be placed in the footer
logo: "./vimlogo-564x564.png" # A path to the book logo
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
